networks:
  static-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16 # Define the subnet for the network

services:
  openssh-server:
    build:
      context: ./
    restart: 'always'
    container_name: openssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUDO_ACCESS=true
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=12345
      - USER_NAME=garry
    ports:
      - 2222:80
    networks:
      static-network:
        ipv4_address: 192.168.0.10 # Assign the static IP